### ISSUE TITLE
Module build failed: Error: Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#80]
Hi,

When I switch on the version 1.2.1 or 1.2.2, I have this error on compilation :
```
$npm start
Failed to compile.

./src/index.js
Module build failed: Error: Cannot find module '@babel/core'
```

When I go back to 1.2.0 it works normally.

I have notices a difference in package-lock.json between the two versions, we have now babel as a requirement :
```
"react-flip-page": {
      "version": "1.2.1",
      "resolved": "https://...",
      "integrity": "sha512-...",
      "requires": {
        "babel-core": "^7.0.0-bridge.0",
        "prop-types": "^15.6.2",
        "react": "^16.4.1",
        "react-dom": "^16.4.1",
        "uglifyjs-webpack-plugin": "^2.0.0"
      }
    }
```
version 1.2.0 :
```
"react-flip-page": {
      "version": "1.2.0",
      "resolved": "https://...",
      "integrity": "sha512-...",
      "requires": {
        "prop-types": "^15.6.2",
        "react": "^16.4.1",
        "react-dom": "^16.4.1",
        "uglifyjs-webpack-plugin": "^1.2.7"
      }
    }
```
I am working on Linux Fedora 28, npm version 6.4.1, node 8.12.0.

Do you think it can be fixed ?

Thank you very much.

**Comment by darenju** [comment]
Hello,

It's weird I didn't get any notification from this repo… let me take a look at this issue, it shouldn't be long.

**Comment by slevy85** [comment]
Yes I cannot reproduce it every time, maybe I was on a project with an old react version...
Anyway, is it normal to have babel as a dependency ? I thought babel was only in the dev/build phase ?

**Comment by darenju** [comment]
You’re right, it should not be included in dependencies. I will try to remove it and build again to see if it changes anything.
